#!/bin/sh

OLDIFS=$IFS
IFS="
"
gradeNum=-3

#this section counts the number of "grades" that exist in the class
for line in $(cat students.csv)
do
	IFS=,	
	for i in $line
	do
		#echo $i
		gradeNum=$((gradeNum+1)) #increment
	done
	break
done

extraUser=$1,$2,$3
i=0
IFS=$OLDIFS
#add the appropriate number of zeros (0) for the new student
while [ $((i)) -ne $((gradeNum)) ]
do
	extraUser=$extraUser,0
	i=$((i+1))
done

#finally add to the end of the file
echo -e $extraUser >> students.csv


